apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: laravel-webapp
  name: laravel-webapp
  namespace: default
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app: laravel-webapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: laravel-webapp
      namespace: default
    spec:
      containers:
      - env:
        - name: APP_NAME
          value: Laravel
        - name: APP_ENV
          value: local
        - name: APP_KEY
          value: base64:
        - name: APP_DEBUG
          value: "true"
        - name: APP_LOG_LEVEL
          value: debug
        - name: LOG_CHANNEL
          value: stack
        - name: DB_CONNECTION
          value: mysql
        - name: DB_HOST
          value: mysql
        - name: DB_DATABASE
          value: 
        - name: DB_USERNAME
          value: 
        - name: DB_PASSWORD
          value: 
        - name: BROADCAST_DRIVER
          value: "pusher"
        - name: CACHE_DRIVER
          value: "redis"
        - name: SESSION_DRIVER
          value: "redis"
        - name: SESSION_LIFETIME
          value: "120"
        - name: QUEUE_DRIVER
          value: "redis"
        - name: REDIS_HOST
          value: "redis-svc"
        - name: REDIS_PASSWORD
          value: "null"
        - name: REDIS_PORT
          value: "6379"
        image: gcr.io/tunitech-project-k8s/laravel-app
        imagePullPolicy: Always
        name: laravel-webapp
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
